console.log('|------------------------------------------------------|')
console.log('|-               cola chicken wings                   -|')
console.log('|-              coding by TypeScript                  -|')
console.log('|-                  江南青衫客                        -|')
console.log('|------------------------------------------------------|\n')